### ISSUE TITLE
SlideOverCard with ScrollView

### ISSUE THREAD

**Issue by mitjans** [moifort/SlideOverCard#4]
Hi! 

I tried to use SlideOverCard with a ScrollView embedded in it and it doesn't work. Any workaround?

Thanks!

**Comment by moifort** [comment]
Hello @mitjans! I don't have a workaround yet, but you can make a PR if you find a way!

**Comment by freddokresna** [comment]
i had this problem too 

but finally i realize my code was to complex to put there , and split it. and now it works with scrollview
